OPEN_AI_KEY=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
MYSQL_HOST=database-1.c90qs4c6wuei.ap-south-1.rds.amazonaws.com
DB_PORT=3306
DB_USER=admin
DB_PASSWORD=Odndigital2025
DB_NAME=ODN_Testing_DB
